config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'users/registrations'}, path: ''
  devise_scope :user do
    root to: 'devise/sessions#new', as: :homepage
  end
  get 'dashboard', to: 'users#show'

  resources :requests, only: [:create, :update]
  resources :evaluations, only: [:update]

  get '/match' => 'tutors#match', as: :tutor_match
  post '/confirm_meeting' => 'tutors#confirm_meeting', as: :tutor_confirm_meeting
  post '/finish_meeting' => 'tutors#finish_meeting', as: :tutor_finish_meeting
  delete '/delete_meeting' => 'tutors#delete_meeting', as: :tutor_delete_meeting

  get '/admin' => 'admins#new', as: :new_admin_session
  post '/admin' => 'admins#create', as: :admin_session
  delete '/admin/sign_out' => 'admins#destroy', as: :admin_logout

  get 'admins/home' => 'admins#home', as: :admin_home
  get 'admins/manage_semester' => 'admins#manage_semester', as: :admin_manage_semester
  get 'admins/toggle_signups' => 'admins#toggle_signups', as: :admin_toggle_signups
  get 'admins/close_unmatched_requests' => 'admins#close_unmatched_requests', as: :admin_close_unmatched_requests
  post 'admins/update_tutor_types' => 'admins#update_tutor_types', as: :admin_update_tutor_types

  get 'admins/rating_tutors' => 'admins#rating_tutors', as: :admin_rating_tutors
  get 'admins/tutor_hours' => 'admins#tutor_hours', as: :admin_tutor_hours
  get 'admins/manage_tutors' => 'admins#manage_tutors', as: :admin_manage_tutors
  post 'admins/manage_tutors/delete_tutor' => 'admins#delete_tutor', as: :admin_delete_tutor
  get 'admins/export_table' => 'admins#export_table', as: :admin_export_table
  post 'admins/update_courses' => 'admins#update_courses', as: :admin_update_courses
  get 'admins/update_password' => 'admins#update_password', as: :admin_update_password
  post 'admins/update_password' => 'admins#post_update_password', as: :admin_post_update_password

  #Admin customize QuestionTemplates routes
  get 'admins/update_question_templates' => 'admins#update_question_templates', as: :admin_update_question_templates
  post 'admins/batch_update' => 'question_templates#batch_update', as: :question_templates_batch_update
  get 'question_templates/get_details' => 'question_templates#get_details'
  get 'question_templates/new' => 'question_templates#new'

  #Used to update Question values (probably just the :response) in Evaluation#update
  patch 'questions/update_response' => 'questions#update_response', as: :question
  put 'questions/update_response' => 'questions#update_response'

  get 'meetings/panel_info' => 'meetings#panel_info'
  get 'evaluations/view_responses' => 'evaluations#view_responses'

end

app/views/admins/_immutable_default_questions.html.haml
%ul.list-group
  %li.list-group-item{sort:false}
    .mb-2= text_field_tag "mandatory_course_prompt", "[CANNOT BE CHANGED] What class did you receive tutoring for?", class:'form-control', disabled:true
    .form-row
      .col-auto.pl-4.pr-3
        .form-row
          %p.mb-1.text-muted
            What type of question is this?
        .form-row.pb-1
          .col-7.pl-0.pr-0
            = select_tag "mandatory_course_is_optional", options_for_select([['Mandatory'], 'Mandatory']), class:'form-control form-control-sm', disabled:true
          .col.pl-1.pr-0
            = select_tag "mandatory_course_question_type", options_for_select(['Dropdown'], 'Dropdown'), class:'form-control form-control-sm', disabled:true
        .form-row
          .col-7.pl-0.pr-0
            = select_tag "mandatory_course_is_admin_only", options_for_select(['Visible to Admin Only'], 'Visible to Admin Only'), class:'form-control form-control-sm', disabled:true
          .col.pl-1.pr-0
            = select_tag "mandatory_course_is_active", options_for_select(['Enabled'],'Enabled'), class:'form-control form-control-sm', disabled:true
      .col-auto.my-auto
        .form-row
          %p.mb-1.text-muted.custom_small
            Options (one per line):
          = text_area_tag "mandatory_course_details_options", 'See Courses Tab for listings', class: 'form-control form-control-sm custom_small', required:'true', disabled:true

  %li.list-group-item{sort:false}
    .mb-2= text_field_tag "mandatory_hours_prompt", "[CANNOT BE CHANGED] How many hours of tutoring did you receive?", class:'form-control', disabled:true
    .form-row
      .col-auto.pl-4.pr-3
        .form-row
          %p.mb-1.text-muted
            What type of question is this?
        .form-row.pb-1
          .col-7.pl-0.pr-0
            = select_tag "mandatory_hours_is_optional", options_for_select([['Mandatory'], 'Mandatory']), class:'form-control form-control-sm', disabled:true
          .col.pl-1.pr-0
            = select_tag "mandatory_hours_question_type", options_for_select(['Scale'], 'Scale'), class:'form-control form-control-sm', disabled:true
        .form-row
          .col-7.pl-0.pr-0
            = select_tag "mandatory_hours_is_admin_only", options_for_select(['Visible to Tutor','Visible to Admin Only'], 'Visible to Tutor'), class:'form-control form-control-sm', disabled:true
          .col.pl-1.pr-0
            = select_tag "mandatory_hours_is_active", options_for_select(['Enabled'],'Enabled'), class:'form-control form-control-sm', disabled:true
      .col-auto.my-auto
        .row
          .col-8
            .form-row
              .col-3
                %p.mb-1.text-muted.custom_small
                  Min Value
                  = text_field_tag "mandatory_hours_details_min_val", 0.0, options={class: 'form-control form-control-sm', type:'number', disabled:true}
              .col
                %p.mb-1.text-muted.custom_small
                  Label
                  = text_field_tag "mandatory_hours_details_min_lab", 'We did not meet', options={class: 'form-control form-control-sm', disabled:true}
            .form-row
              .col-3
                %p.mb-1.text-muted.custom_small
                  Max Value
                  = text_field_tag "mandatory_hours_details_max_val", 4.0, options={class: 'form-control form-control-sm', type:'number', disabled:true}
              .col
                %p.mb-1.text-muted.custom_small
                  Label
                  = text_field_tag "mandatory_hours_details_max_lab", '', options={class: 'form-control form-control-sm', disabled:true}
          .col-4.my-auto
            .form-row
              .col
                %p.mb-1.text-muted.custom_small
                  One word representation
                  = text_field_tag "mandatory_hours_details_descriptor", 'hours', options={class: 'form-control form-control-sm', disabled:true}

app/views/admins/_question_list_item.html.haml
%li.list-group-item
  .mb-2= text_field_tag "qt_#{qt.id}_prompt", qt.prompt, required:'true', class:'form-control'
  .form-row
    .col-auto.pl-4.pr-3
      .form-row
        %p.mb-1.text-muted
          What type of question is this?
      .form-row.pb-1
        .col-7.pl-0.pr-0
          = select_tag "qt_#{qt.id}_is_optional", options_for_select([['Optional',true],['Mandatory',false]], qt.is_optional), options={required:'true', class:'form-control form-control-sm'}
        .col.pl-1.pr-0
          = select_tag "qt_#{qt.id}_question_type", options_for_select([['Text Field','text'],['Numeric Scale','scale'],['Dropdown','dropdown']], qt.question_type), required:'true', class:'form-control form-control-sm', onchange: "showSelectDetails(this);"
      .form-row
        .col-7.pl-0.pr-0
          = select_tag "qt_#{qt.id}_is_admin_only", options_for_select([['Visible to Tutor',false],['Visible to Admin Only',true]], qt.is_admin_only), required:'true', class:'form-control form-control-sm'
        .col.pl-1.pr-0
          = select_tag "qt_#{qt.id}_is_active", options_for_select([['Enabled',true],['Disabled',false]], qt.is_active), required:'true', class:'form-control form-control-sm'
    .col-auto.my-auto{id: "qt_#{qt.id}_select_details"}

app/views/admins/_question_type_dropdown.html.haml
.form-row
  %p.mb-1.text-muted.custom_small
    Options (one per line):
  = text_area_tag "qt_#{id}_details_options", details['options'], options={class: 'form-control form-control-sm custom_small', required:'true'}

app/views/admins/_question_type_scale.html.haml
.row
  .col-8
    .form-row
      .col-3
        %p.mb-1.text-muted.custom_small
          Min Value
          = text_field_tag "qt_#{id}_details_min_val", details['min_val'], options={class: 'form-control form-control-sm', required:'true', type:'number'}
      .col
        %p.mb-1.text-muted.custom_small
          Label
          = text_field_tag "qt_#{id}_details_min_lab", details['min_lab'], options={class: 'form-control form-control-sm', required:'true'}
    .form-row
      .col-3
        %p.mb-1.text-muted.custom_small
          Max Value
          = text_field_tag "qt_#{id}_details_max_val", details['max_val'], options={class: 'form-control form-control-sm', required:'true', type:'number'}
      .col
        %p.mb-1.text-muted.custom_small
          Label
          = text_field_tag "qt_#{id}_details_max_lab", details['max_lab'], options={class: 'form-control form-control-sm', required:'true'}
  .col-4.my-auto
    .form-row
      .col
        %p.mb-1.text-muted.custom_small
          One word representation
          = text_field_tag "qt_#{id}_details_descriptor", details['descriptor'], options={class: 'form-control form-control-sm', required:'true'}

app/views/admins/home.html.haml
.container-fluid
  %ol.breadcrumb
    %li.breadcrumb-item
      %a{:href => '#'} Dashboard
    %li.breadcrumb-item.active Overview

  / Icon Cards
  .row
    .col-xl-3.col-sm-6.mb-3
      .card.text-white.bg-primary.o-hidden.h-100
        .card-body
          .card-body-icon
            %i.glyphicon.glyphicon-comment
          .mr-5 26 New Messages!
        %a.card-footer.text-white.clearfix.small.z-1{:href => '#'}
          %span.float-left View Details
          %span.float-right
            %i.glyphicon.glyphicon-comment
    .col-xl-3.col-sm-6.mb-3
      .card.text-white.bg-warning.o-hidden.h-100
        .card-body
          .card-body-icon
            %i.glyphicon.glyphicon-shopping-cart
          .mr-5 GO BEARS!
        %a.card-footer.text-white.clearfix.small.z-1{:href => '#request'}
          %span.float-left View Details
          %span.float-right
            %i.glyphicon.glyphicon-shopping-cart
    .col-xl-3.col-sm-6.mb-3
      .card.text-white.bg-danger.o-hidden.h-100
        .card-body
          .card-body-icon
            %i.glyphicon.glyphicon-pushpin
          .mr-5 GO TREE!
        %a.card-footer.text-white.clearfix.small.z-1{:href => "#"}
          %span.float-left View Details
          %span.float-right
            %i.glyphicon.glyphicon-pushpin

app/views/admins/landing.html.haml
%body.container.landing_background
  .row.h-100.justify-content-center.align-items-center
    .col-6
      .card.p-4
        = form_tag admin_login_path, class: 'form', id: 'login-form' do
          .h3.text-center.text-info Admin Login
          .form-group
            = label :password, "password", class: 'text-info'
            = password_field_tag :password,'', :placeholder => 'password', class: 'form-control', id:'password'
          = submit_tag 'Login', class: 'btn btn-info btn-md'

-#<%= form_tag admin_login_path do %>
-#  Password: <%= password_field_tag :password %>
-#  <%= submit_tag "Submit" %>
-#
-#<% end %>

app/views/admins/manage_semester.html.haml
.container-fluid

  %ol.breadcrumb
    %li.breadcrumb-item
      %a{:href => '#'} Manage Semester
    %li.breadcrumb-item.active Overview

  .card.mb-3
    .card-header
      %span.glyphicon.glyphicon-pencil
      Edit Tutor Types
    .card-body
      .container-fluid
        .ml-2.mb-2
          Please enter one tutor type per line, with weekly hours requirement in parentheses.
          %br
          Do not leave an empty line at the bottom, or else tutors can select a non-type.
        = form_tag admin_update_tutor_types_path do
          = text_area_tag 'tutor_types', @tutor_types, rows: 5, class: 'form-control'
          = submit_tag 'Update Tutor Types', class:'btn btn-info mt-3'

  .card.mb-3
    .card-header
      %span.glyphicon.glyphicon-pencil
      Update Courses
    .card-body
      .ml-2.mb-2
        Please enter one course per line
        %br
        Do not leave an empty line at the bottom, or else tutees can select a non-type.
      = form_tag admin_update_courses_path do
        = text_area_tag 'course_list', @course_list.join("\n"), rows: 5, class: 'form-control'
        = submit_tag 'Update Course List', class:'btn btn-info mt-3'

  .card.mb-3
    .card-header
      %span.glyphicon.glyphicon-pencil
      Toggle Signups
    .card-body
      .container-fluid
        - if @signups_allowed
          = link_to 'Turn Off Signups', admin_toggle_signups_path, class: "btn btn-info float-left mr-1", id: "toggle_signups"
        - else
          = link_to 'Turn On Signups', admin_toggle_signups_path, class: "btn btn-info float-left mr-1", id: "toggle_signups"

        = link_to 'Close All Unmatched Requests', admin_close_unmatched_requests_path, class: "btn btn-info float-left mr-1", id: "close_requests", data: {confirm: "Are you sure? This will remove all existing unmatched requests. Any students who would like to be tutored will need to create a new request."}

  .card.mb-3
    .card-header
      %span.glyphicon.glyphicon-pencil
      Export All Table Data to CSVs
    .card-body
      .container-fluid
        = link_to 'Export as CSV', admin_export_table_path(query: "all"), class: "btn btn-info", download: true

app/views/admins/manage_tutors.html.haml
.container-fluid


  %ol.breadcrumb
    %li.breadcrumb-item
      %a{:href => '#'} Admin
    %li.breadcrumb-item.active Manage Tutors

  / DataTables Example
  .card.mb-3
    .card-header
      %span.glyphicon.glyphicon-list-alt Tutor Information
    .card-body
      .table-responsive
        %table#dataTable.table.table-bordered{:cellspacing => '0', :width => '100%'}
          %thead
            %tr
              %th Tutor ID
              %th Tutor Name
              %th Tutor Email

            %tfoot
              %tr
              %th Tutor ID
              %th Tutor Name
              %th Tutor Email

          %tbody
            - @tutors.each do |tutor|
              %tr
                %td= tutor.id
                %td= tutor.full_name
                %td= tutor.email

  .card.mb-3
    .card-header
      %span.glyphicon.glyphicon-pencil
      Delete Tutor
    .card-body
      = form_tag admin_delete_tutor_path, class: 'container-fluid' do
        .form-row
          .form-group.col-md-4
            = label :delete_tutor, :email, 'Enter tutor email:'
            = text_field :delete_tutor, :email, class: 'form-control'

        = submit_tag 'Delete Tutor', :id=>'delete_tutor',data: { confirm: "Are you sure? This will remove the tutor from the database as well as any meetings they tutored. This cannot be undone." }, class: 'btn btn-primary'

app/views/admins/new.html.haml
%body.container.landing_background
  .row.h-100.justify-content-center.align-items-center
    .col-6
      .card.p-4
        = form_tag admin_session_path, method: 'post', class: 'form', id: 'login-form' do
          .h3.text-center.text-info Admin Login
          .form-group
            = @logged_in
            = label :password, "password", class: 'text-info'
            = password_field_tag :password,'', :placeholder => 'password', class: 'form-control', id:'password'
          = submit_tag 'Log in', class: 'btn btn-info btn-md'

app/views/admins/rating_tutors.html.haml
.container-fluid

  %ol.breadcrumb
    %li.breadcrumb-item
      %a{:href => '#'} Rating Tutors
    %li.breadcrumb-item.active Overview

  .card.mb-3
    .card-header.justify-content-between.align-items-center
      %span.glyphicon.glyphicon-list-alt Rating Tutors
      -# = link_to 'Export as CSV', admin_export_table_path(query: "tutor_ratings"), class: "btn btn-info float-right", download: true
    .card-body
      - @likert_scale_averages.each do |h|
        = "#{h[0]} average rating:"
        = "#{h[1][0]} out of #{h[1][1]}"
        %br

app/views/admins/tutor_hours.html.haml
.container-fluid


  %ol.breadcrumb
    %li.breadcrumb-item
      %a{:href => '#'} Admin
    %li.breadcrumb-item.active Tutor Hours

  %p{:class => "text-center h4"} CS370 has completed #{@evaluations.total_hours} hours of tutoring this semester!

  / DataTables Example
  #firstTable
    .card.mb-3
      .card-header.justify-content-between.align-items-center
        = button_tag "Tutor Hours", class: "btn glyphicon glyphicon-list-alt", data: {toggle: "collapse", target: "#tutors"}
        = link_to 'Export as CSV', admin_export_table_path(query: "tutor_hours"), id: "export1", class: "btn btn-info float-right", download: true
      .collapse.show{id: "tutors", data: {parent: "#firstTable"}}
        .card-body
          .table-responsive
            %table#dataTable.table.table-bordered{:cellspacing => '0', :width => '100%'}
              %thead
                %tr
                  %th Tutor Email
                  %th Tutor Name
                  %th Total Hours

                %tfoot
                  %tr
                  %th Tutor Email
                  %th Tutor Name
                  %th Total Hours

              %tbody
                - @tutors.each do |tutor|
                  %tr
                    %td= tutor.email
                    %td= tutor.full_name
                    %td= tutor.total_hours

    .card.mb-3
      .card-header.justify-content-between.align-items-center
        = button_tag 'Hours by Demographic', class: "btn glyphicon glyphicon-list-alt", data: {toggle: "collapse", target: "#demographics"}
        = link_to 'Export as CSV', admin_export_table_path(query: "demographic_hours"), id: "export2", class: "btn btn-info float-right", download: true
      .collapse.hide{id: "demographics", data: {parent: "#firstTable"}}
        .card-body
          .table-responsive
            %table#dataTable.table.table-bordered{:cellspacing => '0', :width => '100%'}
              %thead
                %tr
                  %th Ethnicity/Gender
                  %th Total Hours

                %tfoot
                  %tr
                  %th Ethnicity/Gender
                  %th Total Hours

              %tbody
                - @demographics.each do |demographic|
                  %tr
                    - if demographic.eql?("Other")
                      %td= "Other Ethnicity"
                    - else
                      %td= demographic

                    - if ["Male", "Female", "Non-Binary"].any? {|str| str.eql? demographic}
                      %td= @evaluations.hours_gender(demographic)
                    - else
                      %td= @evaluations.hours_ethnicity(demographic)

    .card.mb-3
      .card-header.justify-content-between.align-items-center
        = button_tag 'Hours by Course', class: "btn glyphicon glyphicon-list-alt", data: {toggle: "collapse", target: "#course"}
        = link_to 'Export as CSV', admin_export_table_path(query: "course_hours"), id: "export3", class: "btn btn-info float-right", download: true
      .collapse.hide{id: "course", data: {parent: "#firstTable"}}
        .card-body
          .table-responsive
            %table#dataTable.table.table-bordered{:cellspacing => '0', :width => '100%'}
              %thead
                %tr
                  %th Course
                  %th Total Hours

                %tfoot
                  %tr
                  %th Course
                  %th Total Hours

              %tbody
                - @courses.each do |course|
                  %tr
                    %td= course
                    %td= @evaluations.hours_course(course)

app/views/admins/updateCurrentSemester.haml
.container-fluid


  / Breadcrumbs
  %ol.breadcrumb
    %li.breadcrumb-item
      %a{:href => '#'} Dashboard
    %li.breadcrumb-item.active Overview

  .card.mb-3
    .card-header
      %span.glyphicon.glyphicon-dashboard
      Current Semester: #{@current_semester}
  .card.mb-3
    .card-header
      %span.glyphicon.glyphicon-pencil
      Update Current Semester
    .card-body
      - if flash[:curr_message]
        .alert.alert-danger
          %span.error= flash[:curr_message]
      = form_tag admin_update_current_semester_path, class: 'container-fluid' do
        .form-row
          .form-group.col-md-4
            = label :update_current_semester, :semester, 'Please pick a semester:'
            = select :update_current_semester, :semester, options_for_select(@semester_options), {:id =>'semester_list'}, class: 'form-control'
          .form-group.col-md-4
            = label :update_current_semester, :year, 'Year'
            = text_field :update_current_semester, 'year', class: 'form-control', :placeholder => 'e.g. 2019', :required => "",
              :oninput => "this.setCustomValidity('')", :oninvalid => "this.setCustomValidity('Cannot be empty')"

        = submit_tag 'Update current semester', :id=>'update_current_semester',data: { confirm: "Are you sure? This will change the current semester for the whole site! Not just the admins view. This should be done only once at the end of the semester." }, class: 'btn btn-primary'

app/views/admins/update_question_templates.html.haml
.container-fluid
  %ol.breadcrumb
    %li.breadcrumb-item
      %a{:href => '#'} Update Evaluation Questions
    %li.breadcrumb-item.active Overview
  = form_tag question_templates_batch_update_path, id: 'submit_batch_update' do
    = submit_tag 'Update Question Templates and Layout', class:'btn btn-primary m-2'
    = render partial: 'immutable_default_questions'
    %ul.list-group{id: 'question_template_list'}
      -@question_templates.each do |qt|
        = render partial: 'question_list_item', locals:{qt: qt}
  = button_tag 'Add Question', type: 'button', class:'btn btn-primary m-2', id: 'create_question_template'

app/views/admins/update_semester.haml
.container-fluid


  / Breadcrumbs
  %ol.breadcrumb
    %li.breadcrumb-item
      %a{:href => '#'} Dashboard
    %li.breadcrumb-item.active Overview

  .card.mb-3
    .card-header
      %span.glyphicon.glyphicon-dashboard
      Current Semester: #{@current_semester}
  .card.mb-3
    .card-header
      %span.glyphicon.glyphicon-pencil
      Update Current Semester
    .card-body
      - if flash[:curr_message]
        .alert.alert-danger
          %span.error= flash[:curr_message]
      = form_tag admin_update_current_semester_path, class: 'container-fluid' do
        .form-row
          .form-group.col-md-4
            = label :update_current_semester, :semester, 'Please pick a semester:'
            = select :update_current_semester, :semester, options_for_select(@semester_options), {:id =>'semester_list'}, class: 'form-control'
          .form-group.col-md-4
            = label :update_current_semester, :year, 'Year'
            = text_field :update_current_semester, 'year', class: 'form-control', :placeholder => 'e.g. 2019', :required => "",
              :oninput => "this.setCustomValidity('')", :oninvalid => "this.setCustomValidity('Cannot be empty')"

        = submit_tag 'Update current semester', :id=>'update_current_semester',data: { confirm: "Are you sure? This will change the current semester for the whole site! Not just the admins view. This should be done only once at the end of the semester." }, class: 'btn btn-primary'