config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'users/registrations'}, path: ''
  devise_scope :user do
    root to: 'devise/sessions#new', as: :homepage
  end
  get 'dashboard', to: 'users#show'

  resources :requests, only: [:create, :update]
  resources :evaluations, only: [:update]

  get '/match' => 'tutors#match', as: :tutor_match
  post '/confirm_meeting' => 'tutors#confirm_meeting', as: :tutor_confirm_meeting
  post '/finish_meeting' => 'tutors#finish_meeting', as: :tutor_finish_meeting
  delete '/delete_meeting' => 'tutors#delete_meeting', as: :tutor_delete_meeting

  get '/admin' => 'admins#new', as: :new_admin_session
  post '/admin' => 'admins#create', as: :admin_session
  delete '/admin/sign_out' => 'admins#destroy', as: :admin_logout

  get 'admins/home' => 'admins#home', as: :admin_home
  get 'admins/manage_semester' => 'admins#manage_semester', as: :admin_manage_semester
  get 'admins/toggle_signups' => 'admins#toggle_signups', as: :admin_toggle_signups
  get 'admins/close_unmatched_requests' => 'admins#close_unmatched_requests', as: :admin_close_unmatched_requests
  post 'admins/update_tutor_types' => 'admins#update_tutor_types', as: :admin_update_tutor_types

  get 'admins/rating_tutors' => 'admins#rating_tutors', as: :admin_rating_tutors
  get 'admins/tutor_hours' => 'admins#tutor_hours', as: :admin_tutor_hours
  get 'admins/manage_tutors' => 'admins#manage_tutors', as: :admin_manage_tutors
  post 'admins/manage_tutors/delete_tutor' => 'admins#delete_tutor', as: :admin_delete_tutor
  get 'admins/export_table' => 'admins#export_table', as: :admin_export_table
  post 'admins/update_courses' => 'admins#update_courses', as: :admin_update_courses
  get 'admins/update_password' => 'admins#update_password', as: :admin_update_password
  post 'admins/update_password' => 'admins#post_update_password', as: :admin_post_update_password

  #Admin customize QuestionTemplates routes
  get 'admins/update_question_templates' => 'admins#update_question_templates', as: :admin_update_question_templates
  post 'admins/batch_update' => 'question_templates#batch_update', as: :question_templates_batch_update
  get 'question_templates/get_details' => 'question_templates#get_details'
  get 'question_templates/new' => 'question_templates#new'

  #Used to update Question values (probably just the :response) in Evaluation#update
  patch 'questions/update_response' => 'questions#update_response', as: :question
  put 'questions/update_response' => 'questions#update_response'

  get 'meetings/panel_info' => 'meetings#panel_info'
  get 'evaluations/view_responses' => 'evaluations#view_responses'

end

app/models/tutor.rb
class Tutor < User
  has_many :meetings
  has_many :evaluations, through: :meetings

  def full_name
    self.first_name + ' ' + self.last_name
  end

  def total_hours
    @all_evals = self.evaluations
    return @all_evals.sum(:hours)
  end

  def hours_this_week
    return self.evaluations.where(created_at: Time.now.beginning_of_week.strftime("%Y-%m-%d")..Time.now).sum(:hours)
  end

end

app/controllers/tutors_controller.rb
require 'date'
class TutorsController < ApplicationController
  # GET /tutors
  # GET /tutors.json
  def index
    @tutors = Tutor.all
  end

  def finish_meeting
    @meeting = Meeting.find_by_id(params['finish-meeting-hidden-field'])
    tid = session[:current_user_id]
    sid = @meeting.tutee.id

    begin
      TutorMailer.meeting_complete_notice(tid, sid).deliver_now
    rescue StandardError
      flash[:notice] = "An error occured when sending out emails. Meeting was not marked as complete, please contact an administrator if this error persists."
    else
      flash[:success] = "Your meeting was successfully finished."
      @eval = Evaluation.create(meeting_id: @meeting.id)
      QuestionTemplate.ordered_list_of_question_templates.each do |qt|
        if qt.is_active
          Question.create(evaluation_id: @eval.id, question_template_id: qt.id, prompt: qt.prompt, is_admin_only: qt.is_admin_only)
        end
      end
      @meeting.update!(status: 'finished')
    end

    redirect_back(fallback_location:"/")
  end

  def delete_meeting
    meeting = Meeting.find_by_id(params['delete-meeting-hidden-field'])
    #open request for tutee and for other tutors
    meeting.request.update(status: "open")
    meeting.destroy()

    flash[:success] = "Your meeting was successfully cancelled."
    redirect_back(fallback_location:"/")
  end

  def confirm_meeting
    @meeting = Meeting.find(params["meeting_id"])
    @tutor_id = @meeting.tutor.id
    @tutee_id = @meeting.tutee.id
    @request_id = @meeting.request.id
    @time = Time.strptime(params["meeting_date"] + params["meeting_time"], "%Y-%m-%d%H:%M")
    @loc = params[:meeting_location]

    tutor_message = "Hi, your meeting has been confirmed for " + @time.strftime("%A, %b %d at %l:%M %p") + " at " + @loc + "."

    begin
      TutorMailer.meeting_confirmation(@tutor_id, @tutee_id, tutor_message, @request_id).deliver_now
    rescue StandardError
      flash[:notice] = "An error occured when sending out confirmation emails."
    else
      flash[:success] = "Successfully confirmed meeting details!"
      @meeting.update(set_time: @time, set_location: @loc, status: 'scheduled');
    end
    redirect_back(fallback_location:"/")
  end

  def match
    tutor_id = session[:current_user_id]
    tutee_email = params[:tutee_email]
    tutee_id = Tutee.find_by_email(tutee_email).id
    request_id = params[:request_id]
    tutor_message = params[:tutor_message]
    begin
      TutorMailer.invite_student(tutor_id, tutee_id, request_id, tutor_message).deliver_now
    rescue StandardError
      flash[:notice] = "An error occured when sending out emails."
    else
      flash[:success] = "Successfully matched!"
      Meeting.create!(tutor_id: tutor_id, request_id: request_id, status: 'unscheduled')
      Request.find(request_id).update(status: 'matched')
    end
    redirect_back(fallback_location:"/")
  end

  # GET /tutors/1
  # GET /tutors/1.json
  def show
    @tutor = Tutor.find_by_id(params[:id])
    @meetings = Meeting.where("tutor_id = ? AND status = pending", params[:id])
    @previous_meetings = Meeting.where("tutor_id = ? AND status = finished", params[:id])
  end

  # GET /tutors/new
  def new
    @tutor = Tutor.new
  end

  # GET /tutors/1/edit
  def edit
  end

  def total_hours
    @tutor= Tutor.find(params[:id])
    return Tutor.total_hours_helper(@tutor)
  end
  helper_method :total_hours


  def hours_this_week
    @tutor= Tutor.find(params[:id])
    return Tutor.hours_this_week_helper(@tutor)
  end
  helper_method :hours_this_week

  def average_hours
    @tutor= Tutor.find(params[:id])
    return Tutor.average_hours_helper(@tutor)
  end
  helper_method :average_hours

  def update
    #This should move to Devise ASAP.
    #NOTE: you can actually change emails, and it will send a confirmation email that, once confirmed, will update your email address.
    #This could be cool, but also you only have one berkeley email, so you shouldn't be allowed to change your email associated with this acc.
    processed_major = tutor_params
    processed_major[:major] = process_major_input params['tutor']['major']
    if @tutor.update(processed_major)
      flash[:success] = "Changes saved"
    else
      flash[:notice] = "Changes not saved"
    end
    redirect_to tutor_path(@tutor)
  end

  def destroy

  end

  def requests

  end

end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/tutors/_panel_evaluation_responses.html.haml
%div.font-weight-light{id:"panel-evaluation-responses", style: "display: none"}
  .lead.card-title.text-center.mb-0 Your Evaluation
  %span.glyphicon.glyphicon-remove{style:"cursor: pointer; color:red; position:absolute; right:0.5vw; top:1vh", onclick: "showTutorPanel('statistics',null)"}
  %hr.my-1
  %span{id: 'evaluation-responses-holder-id'}

app/views/tutors/_panel_invite_form.html.haml
=form_tag tutor_match_path(@user), id:"panel-invite-form", style: "display: none;", method:"get" do
  .lead.card-title.text-center.mb-0 Send Invitation
  %span.glyphicon.glyphicon-remove{style:"cursor: pointer; color:red; position:absolute; right:0.5vw; top:1vh", onclick: "showTutorPanel('statistics',null)"}
  %hr.my-1
  .form-group.my-1
    .font-weight-light.pl-2{id:'to-email'}
    .font-weight-light.pl-2 Subject - CS370 Tutoring
  = hidden_field_tag 'tutee_email'
  = hidden_field_tag 'request_id'
  .form-group
    = text_area_tag 'tutor_message', "", placeholder: "Your message will be preceded by an auto-generated section introducing you and the request information.", rows: 6, class:"form-control", style:"font-weight: lighter"
  .form-group.mb-1
    = submit_tag 'Send Invite', class: "btn btn-block btn-success", style:"font-weight: lighter"

app/views/tutors/_panel_meeting_details.html.haml
%div{id:"panel-meeting-details", style: "display: none;"}
  =form_tag tutor_confirm_meeting_path(@user), method:"post" do
    .lead.card-title.text-center.mb-0 Meeting Details
    %span.glyphicon.glyphicon-remove{style:"cursor: pointer; color:red; position:absolute; right:0.5vw; top:1vh", onclick: "showTutorPanel('statistics', null)"}
    %hr.my-1
    .form-group.my-1
      .font-weight-light.pl-2 Your meeting with:
      .font-weight-light.pr-2.text-right{id:'tutee-name'}
    = hidden_field_tag 'meeting_id'
    .form-row.pb-1
      = date_field_tag 'meeting_date', '', class: 'form-control form-control-sm', style:"font-weight: lighter", label: "meeting_date"
    .form-row.pb-1
      = time_field_tag 'meeting_time', '', class: 'form-control form-control-sm', style:"font-weight: lighter"
    .form-row.mb-2
      = text_field_tag 'meeting_location', '', placeholder:'Meeting Location', class: 'form-control form-control-sm', style: "padding-right: 30px; font-weight: lighter"
      %span.glyphicon.glyphicon-map-marker{style:"position:absolute; right:0; padding:5px 22px"}
    = submit_tag 'Confirm Meeting', class: 'btn btn-block btn-success', style:"font-weight: lighter", id: 'confirm-meeting-button'
  =form_tag tutor_finish_meeting_path, id: 'finish-meeting-button', method:"post" do
    = submit_tag 'Finish Meeting', data: {confirm: "Warning! You are finishing a meeting, the action cannot be undone."}, class: 'btn btn-block btn-success', style:"font-weight: lighter"
    = hidden_field_tag 'finish-meeting-hidden-field'
  =form_tag tutor_delete_meeting_path, id: 'delete-meeting-button', method:"delete" do
    = submit_tag 'Delete Meeting', data: {confirm: "Warning! You are deleting a meeting, the action cannot be undone."}, class: 'btn btn-block btn-danger', style:"font-weight: lighter"
    = hidden_field_tag 'delete-meeting-hidden-field'

app/views/tutors/_panel_tutoring_statistics.html.haml
%div.font-weight-light{id:"panel-tutoring-statistics"}
  .lead.card-title.text-center.mb-0 Your Statistics
  %hr.my-1
  .row
    .col-9.text-right
      Total Hours Tutored:
    .col-3.pl-0
      69
  .row
    .col-9.text-right
      Hours This Week:
    .col-3.pl-0
      3
  .row
    .col-9.text-right
      Total Hours Remaining:
    .col-3.pl-0
      10
  .lead.card-title.text-center.mb-0.mt-4 CS370 Statistics
  %hr.my-1
  .row
    .col-9.text-right
      Total Hours Tutored:
    .col-3.pl-0
      69
  .row
    .col-9.text-right
      Hours This Week:
    .col-3.pl-0
      3

app/views/tutors/_table_find_tutees.html.haml
%ul.nav.nav-tabs.nav-justified{role:'tablist'}
  - Admin.course_list.each do |course|
    %li.nav-item
      %a.nav-link{id: "#{course}-tab", role: 'tab', 'data-toggle':'tab', href: "##{course}", 'aria-controls': "#{course}"}= course
.tab-content
  - Admin.course_list.each do |course|
    .tab-pane.fade{id: "#{course}", role:'tabpanel', 'aria-labelledby': "#{course}-tab"}
      - if Request.get_open_requests_by_course(course).length == 0
        .row.w-100.align-items-center.text-center{style:"min-height: 30vh"}
          .col
            ="There are no requests for #{course} at this time."
      - else
        %table.table.table-hover.table-responsive-lg{id: "#{course}-table"}
          %thead.thead-light
            %tr
              %th{scope: 'col'} #
              %th{scope: 'col'} Tutee Name
              %th{scope: 'col'} Subject
              %th{scope: 'col'} Duration Requested
          %tbody
            - Request.get_open_requests_by_course(course).each_with_index do |request, index|
            - tutee = request.tutee
              %tr{style: "cursor: pointer;", onclick:"showTutorPanel('tutee',['#{tutee.email}','#{request.id}']);", id: "row_#{index}"}
                %th{scope: 'row'}= index+1
                %td= tutee.full_name
                %td= request.subject
                %td= (request.meeting_length*60).to_i.to_s + " min"

app/views/tutors/_table_previous_meetings.html.haml
- if @previous_meetings.length == 0
  .row.w-100.h-100.align-items-center.text-center
    .col
      You have no previous meetings, meetings marked as finished will show up here.
- else
  %table.table.table-hover.table-responsive-lg
    %thead.thead-light
      %tr
        %th{scope: 'col'} #
        %th{scope: 'col'} Course
        %th{scope: 'col'} Subject
        %th{scope: 'col'} Duration
        %th{scope: 'col'} Time
        %th{scope: 'col'} Location
    %tbody
      - @previous_meetings.each_with_index do |meeting, index|
        %tr{style: "cursor: pointer;", onclick:"showTutorPanel('previous', [#{meeting.id}]);", id: "row_#{index}"}
          %th.align-middle{scope: 'row'}= index+1
          %td.align-middle= meeting.request.course
          %td.align-middle= meeting.request.subject
          %td.align-middle= (meeting.request.meeting_length*60).to_i.to_s + " min"
          %td.align-middle= meeting.set_time ? meeting.set_time.strftime("%b %d, %Y at %I:%M%P") : "Pending Confirmation"
          %td.align-middle= meeting.set_location ? meeting.set_location : "Pending Confirmation"

app/views/tutors/_table_upcoming_meetings.html.haml
- if @meetings.length == 0
  .row.w-100.h-100.align-items-center.text-center
    .col
      You have no upcoming meetings, find tutees to tutor in the adjacent tab.
- else
  %table.table.table-hover.table-responsive-lg
    %thead.thead-light
      %tr
        %th{scope: 'col'} #
        %th{scope: 'col'} Tutee Name
        %th{scope: 'col'} Course
        %th{scope: 'col'} Subject
        %th{scope: 'col'} Duration
        %th{scope: 'col'} Time
        %th{scope: 'col'} Location
        %th{scope: 'col'} Contact
      %tbody
        - @meetings.each_with_index do |meeting, index|
          - tutee = meeting.tutee
          - request = meeting.request
          %tr{style: "cursor: pointer;", onclick:"showTutorPanel('upcoming', ['#{tutee.full_name}', '#{meeting.id}']);", id:"row_#{index}"}
            %th.align-middle{scope: 'row'}= index+1
            %td.align-middle= tutee.full_name
            %td.align-middle= request.course
            %td.align-middle= request.subject
            %td.align-middle= (request.meeting_length*60).to_i.to_s + " min"
            %td.align-middle= meeting.set_time ? meeting.set_time.strftime("%b %d, %Y at %I:%M%P") : "Pending Confirmation"
            %td.align-middle= meeting.set_location ? meeting.set_location : "Pending Confirmation"
            %td.align-middle= tutee.email