config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'users/registrations'}, path: ''
  devise_scope :user do
    root to: 'devise/sessions#new', as: :homepage
  end
  get 'dashboard', to: 'users#show'

  resources :requests, only: [:create, :update]
  resources :evaluations, only: [:update]

  get '/match' => 'tutors#match', as: :tutor_match
  post '/confirm_meeting' => 'tutors#confirm_meeting', as: :tutor_confirm_meeting
  post '/finish_meeting' => 'tutors#finish_meeting', as: :tutor_finish_meeting
  delete '/delete_meeting' => 'tutors#delete_meeting', as: :tutor_delete_meeting

  get '/admin' => 'admins#new', as: :new_admin_session
  post '/admin' => 'admins#create', as: :admin_session
  delete '/admin/sign_out' => 'admins#destroy', as: :admin_logout

  get 'admins/home' => 'admins#home', as: :admin_home
  get 'admins/manage_semester' => 'admins#manage_semester', as: :admin_manage_semester
  get 'admins/toggle_signups' => 'admins#toggle_signups', as: :admin_toggle_signups
  get 'admins/close_unmatched_requests' => 'admins#close_unmatched_requests', as: :admin_close_unmatched_requests
  post 'admins/update_tutor_types' => 'admins#update_tutor_types', as: :admin_update_tutor_types

  get 'admins/rating_tutors' => 'admins#rating_tutors', as: :admin_rating_tutors
  get 'admins/tutor_hours' => 'admins#tutor_hours', as: :admin_tutor_hours
  get 'admins/manage_tutors' => 'admins#manage_tutors', as: :admin_manage_tutors
  post 'admins/manage_tutors/delete_tutor' => 'admins#delete_tutor', as: :admin_delete_tutor
  get 'admins/export_table' => 'admins#export_table', as: :admin_export_table
  post 'admins/update_courses' => 'admins#update_courses', as: :admin_update_courses
  get 'admins/update_password' => 'admins#update_password', as: :admin_update_password
  post 'admins/update_password' => 'admins#post_update_password', as: :admin_post_update_password

  #Admin customize QuestionTemplates routes
  get 'admins/update_question_templates' => 'admins#update_question_templates', as: :admin_update_question_templates
  post 'admins/batch_update' => 'question_templates#batch_update', as: :question_templates_batch_update
  get 'question_templates/get_details' => 'question_templates#get_details'
  get 'question_templates/new' => 'question_templates#new'

  #Used to update Question values (probably just the :response) in Evaluation#update
  patch 'questions/update_response' => 'questions#update_response', as: :question
  put 'questions/update_response' => 'questions#update_response'

  get 'meetings/panel_info' => 'meetings#panel_info'
  get 'evaluations/view_responses' => 'evaluations#view_responses'

end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert alert-danger"><%= alert %></p>

app/views/layouts/admin_layout.html.haml
!!!
%html{:lang => 'en'}
  %head
    %meta{:content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}/
    %meta{:charset => 'utf-8'}/
    %meta{:content => 'IE=edge', 'http-equiv' => 'X-UA-Compatible'}/
    %meta{:content => 'width=device-width, initial-scale=1, shrink-to-fit=no', :name => 'viewport'}/
    %meta{:content => '', :name => 'description'}/
    %meta{:content => '', :name => 'author'}/
    %title CS370
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'dataTables.bootstrap4.min.css'
    = csrf_meta_tags

  %body#page-top

    / Navbar
    %nav.navbar.navbar-expand.navbar-dark.bg-dark.static-top
      %a.navbar-brand.mr-1.glyphicon.glyphicon-user{:href => '#'} Admin Home
      .d-none.d-md-inline-block.form-inline.ml-auto.mr-0.mr-md-3.my-2.my-md-0
        .input-group
          .input-group-append
            %a.navbar-brand.mr-1{:href => '#'} CS370
    / Navbar end
    = render 'application/notice'
    #wrapper
      / Sidebar
      %ul.sidebar.navbar-nav
        %li.nav-item.post{:class => "#{'active' if current_page?(admin_home_path)}"}
          %a.nav-link{:href => admin_home_path}
            %span.glyphicon.glyphicon-dashboard
            %span Dashboard
        %li.nav-item.post{:class => "#{'active' if current_page?(admin_rating_tutors_path)}"}
          %a.nav-link{:href => admin_rating_tutors_path}
            %span.glyphicon.glyphicon-list-alt
            %span Tutor Ratings
        %li.nav-item.post{:class => "#{'active' if current_page?(admin_tutor_hours_path)}"}
          %a.nav-link{:href => admin_tutor_hours_path}
            %span.glyphicon.glyphicon-list-alt
            %span Tutor Hours
        %li.nav-item.post{:class => "#{'active' if current_page?(admin_manage_tutors_path)}"}
          %a.nav-link{:href => admin_manage_tutors_path}
            %span.glyphicon.glyphicon-list-alt
            %span Manage Tutors
        %li.nav-item.post{:class => "#{'active' if current_page?(admin_manage_semester_path)}"}
          %a.nav-link{:href => admin_manage_semester_path}
            %span.glyphicon.glyphicon-folder-close
            %span Manage Semester
        %li.nav-item.post{:class => "#{'active' if current_page?(admin_update_question_templates_path)}"}
          %a.nav-link{:href => admin_update_question_templates_path}
            %span.glyphicon.glyphicon-folder-close
            %span Update Evaluation Questions
        %li.nav-item.post{:class => "#{'active' if current_page?(admin_update_password_path)}"}
          %a.nav-link{:href => admin_update_password_path}
            %span.glyphicon.glyphicon-folder-close
            %span Update Password
        %li.nav-item
          %a.nav-link{:href => admin_logout_path, 'data-method': 'delete'}
            %span.glyphicon.glyphicon-off
            %span Log Out
        / Sidebar end

      #content-wrapper
        = yield
        / Sticky Footer
        %footer.sticky-footer
          .container.my-auto
            .copyright.text-center.my-auto
              %span Copyright © UC Berkeley 2019

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cs370</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'dataTables.bootstrap4.min.css' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>